In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print("Modules imported")

Modules imported

In [2]:
train_data = pd.read_csv('archive/train.csv')
train_data.head()

,Unnamed: 0,description_x,description_y,ticker_x,ticker_y,same_security
0,0,first trust dow jones internet,first trust dj internet idx,FDN,FDN,True
1,1,schwab intl large company index etf,schwab strategic tr fundamental intl large co ...,FNDF,FNDF,True
2,2,vanguard small cap index adm,vanguard small-cap index fund inst,VSMAX,VSCIX,False
3,3,duke energy corp new com new isin #us4 sedol #...,duke energy corp new com new isin #us26441c204...,DUK,DUK,True
4,4,visa inc class a,visa inc.,V,V,True

In [3]:
train_data.drop(train_data.columns[0], axis = 1, inplace = True)
train_data.head()

,description_x,description_y,ticker_x,ticker_y,same_security
0,first trust dow jones internet,first trust dj internet idx,FDN,FDN,True
1,schwab intl large company index etf,schwab strategic tr fundamental intl large co ...,FNDF,FNDF,True
2,vanguard small cap index adm,vanguard small-cap index fund inst,VSMAX,VSCIX,False
3,duke energy corp new com new isin #us4 sedol #...,duke energy corp new com new isin #us26441c204...,DUK,DUK,True
4,visa inc class a,visa inc.,V,V,True

In [4]:
train_data['same_security'] = train_data['same_security'].astype('int')
train_data.head()

,description_x,description_y,ticker_x,ticker_y,same_security
0,first trust dow jones internet,first trust dj internet idx,FDN,FDN,1
1,schwab intl large company index etf,schwab strategic tr fundamental intl large co ...,FNDF,FNDF,1
2,vanguard small cap index adm,vanguard small-cap index fund inst,VSMAX,VSCIX,0
3,duke energy corp new com new isin #us4 sedol #...,duke energy corp new com new isin #us26441c204...,DUK,DUK,1
4,visa inc class a,visa inc.,V,V,1

In [5]:
df = train_data[['description_x', 'description_y', 'same_security']]
df.head()

,description_x,description_y,same_security
0,first trust dow jones internet,first trust dj internet idx,1
1,schwab intl large company index etf,schwab strategic tr fundamental intl large co ...,1
2,vanguard small cap index adm,vanguard small-cap index fund inst,0
3,duke energy corp new com new isin #us4 sedol #...,duke energy corp new com new isin #us26441c204...,1
4,visa inc class a,visa inc.,1

In [6]:
df.same_security.value_counts()

same_security
1    1613
0     529
Name: count, dtype: int64

In [7]:
from tensorflow.keras.layers import TextVectorization

text_vectorizer = TextVectorization(max_tokens=None,
                                    standardize = "lower_and_strip_punctuation",
                                    split = "whitespace",
                                    ngrams = None,
                                    output_mode = 'int',
                                    output_sequence_length = None)

In [8]:
train_sentences1 = train_data.description_x
train_sentences2 = train_data.description_y

text_vectorizer.adapt(train_sentences1)

In [9]:
sample_sentence = "This is a sample sentence, there is flood on my street, what are you doing? I am just waiting at the door staep"
text_vectorizer([sample_sentence])

<tf.Tensor: shape=(1, 23), dtype=int64, numpy=
array([[   1,  319,   11,    1,    1,    1,  319,    1,    1,    1,  574,
           1,    1,    1,    1,   33,  772,    1,    1, 1380,  148,    1,
           1]])>

In [10]:
train_sentences1 = train_data.description_x
train_sentences2 = train_data.description_y

text_vectorizer.adapt(train_sentences1)

vectorized_sentences1 = text_vectorizer(train_sentences1)
vectorized_sentences2 = text_vectorizer(train_sentences2)

In [11]:
import random

random_sentence = random.choice(train_sentences1)
print(f'Original Sentence: {random_sentence}')
print(f'Vectorized Sentence: {text_vectorizer([random_sentence])}')

Original Sentence: alcoa inc. cmn
Vectorized Sentence: [[1410    3   64]]

In [12]:
print(f'Original Sentence: pimco real return insitutional')
print(text_vectorizer(['pimco real return insitutional']))

Original Sentence: pimco real return insitutional
tf.Tensor([[ 14  86  19 478]], shape=(1, 4), dtype=int64)

In [13]:
from tensorflow.keras.layers import Embedding

embedding = Embedding(input_dim = 10000,
                      output_dim = 128,
                      )

embedding

In [14]:
random_sentence = random.choice(train_sentences1)
print(f'Original Sentence : {random_sentence}')
print(f'Embedded Sentence: {embedding(text_vectorizer([random_sentence]))}')

Original Sentence : netflix com inc com
Embedded Sentence: [[[ 4.11355831e-02 -1.88316237e-02 -3.47595587e-02  3.13498713e-02
    4.70520593e-02 -3.88949998e-02  4.39442433e-02  2.25008167e-02
   -3.09179910e-02 -8.28498602e-03 -2.64773499e-02 -4.66058739e-02
   -4.58112471e-02 -3.17972191e-02 -1.59754641e-02  3.71273495e-02
   -2.35708486e-02  3.46793272e-02  3.84248830e-02 -3.47946398e-02
   -4.07620668e-02  2.64162533e-02 -1.76743865e-02 -2.42166519e-02
   -4.62828279e-02 -1.83624513e-02  2.95548700e-02 -2.59251483e-02
    4.42397706e-02 -2.09423155e-03 -3.24372277e-02  1.04143471e-03
   -3.94493341e-02  3.52171324e-02  2.42753737e-02 -1.00161545e-02
   -4.14825901e-02  2.00820677e-02 -4.68550920e-02 -3.08109280e-02
    3.39345373e-02  1.88003518e-02 -4.75884564e-02 -7.86708668e-03
    4.42726873e-02  2.45322026e-02  3.77613790e-02  2.51512602e-03
    2.51176991e-02 -3.27288657e-02 -2.77495515e-02  1.45868212e-03
    3.13366987e-02 -3.61481421e-02  4.03828137e-02  3.86841409e-02
    5.97470999e-03  2.58715637e-02  1.38795115e-02 -4.42345254e-02
   -1.16626620e-02 -7.25984573e-04 -3.09572350e-02 -2.50773784e-02
    3.04160975e-02 -3.40331942e-02  4.90929522e-02  3.15969326e-02
    1.63095482e-02 -1.29578821e-02 -5.11389971e-03  9.85383987e-03
    1.99291147e-02  5.73241711e-03  2.16637738e-02  2.88118459e-02
    4.85114343e-02 -5.32885641e-03 -4.54354547e-02  4.49535288e-02
    4.72818501e-02 -4.14224043e-02  3.12395729e-02  1.20303780e-03
   -3.89089808e-02  3.50737609e-02  4.46445085e-02 -1.59000531e-02
    3.16777714e-02  2.85822265e-02  4.89365943e-02 -2.81719696e-02
   -2.38586217e-04  1.62061937e-02  1.58966891e-02 -8.20600986e-03
   -3.69631425e-02  3.72379161e-02 -2.10850965e-02  3.01501900e-03
    1.95106976e-02  8.38972256e-03 -2.25110780e-02 -5.07760793e-04
   -3.58675495e-02  2.42329575e-02  4.02140357e-02 -4.12685387e-02
    3.78764309e-02  2.72332169e-02 -1.54384486e-02 -1.74066536e-02
    1.58215426e-02 -2.27332842e-02 -4.37596440e-02 -2.11377144e-02
    2.79269107e-02  3.87302972e-02  2.12145112e-02 -1.95473190e-02
    4.21265401e-02 -2.61827242e-02  2.81510465e-02  2.09002011e-02
    9.87987593e-03 -1.36965401e-02  3.94052900e-02 -4.07909267e-02]
  [ 2.84221806e-02 -2.37033851e-02  3.98677588e-03  3.41418125e-02
   -1.58490650e-02  4.21768092e-02 -1.88158397e-02  4.01492380e-02
   -2.73007639e-02 -7.44471699e-03  8.16166401e-03 -1.58831105e-02
   -4.44130562e-02 -4.30429950e-02  1.26409195e-02 -9.11878422e-03
   -4.31329869e-02 -1.31073222e-02 -3.70266922e-02  1.44015662e-02
   -1.04658008e-02 -1.34580135e-02 -4.23724167e-02 -4.86696735e-02
   -1.43713877e-03 -4.87720966e-02  3.78739499e-02 -2.90668495e-02
   -4.25593928e-03 -1.83375850e-02  4.39928845e-03 -6.45779073e-04
    3.07251252e-02 -4.40380462e-02  4.42527644e-02  1.26951933e-03
   -6.92967325e-03  4.41037752e-02  1.92197226e-02  9.78195667e-03
   -2.46602185e-02 -7.13096932e-03 -3.65925543e-02 -4.65849303e-02
   -2.66242158e-02  4.77626957e-02 -2.50626802e-02 -3.91223058e-02
   -1.36644952e-02  1.51385553e-02  3.96771170e-02  4.13556211e-02
   -9.90567356e-03 -3.07295807e-02 -2.87271496e-02 -3.24951895e-02
   -3.78066301e-03 -4.21069562e-04  1.07317194e-02  2.40976475e-02
   -3.31627205e-03  2.53432654e-02 -2.07371358e-02 -7.33792782e-03
    4.58741076e-02  3.00190337e-02 -1.89627167e-02  4.37664986e-03
    8.89388472e-03 -1.58028826e-02  3.12719680e-02 -2.39773523e-02
   -4.37222980e-02  4.77913134e-02  1.28597058e-02 -6.15016371e-03
   -3.75545248e-02  8.53694975e-04  3.02889980e-02  2.43637078e-02
    1.71693303e-02 -3.85473259e-02  1.96368434e-02 -9.49463993e-03
    8.67988914e-03 -3.41167338e-02 -3.98877747e-02  6.04167581e-05
   -1.19357593e-02  4.61945571e-02 -1.29919760e-02 -2.84509417e-02
   -2.84285676e-02  6.27901405e-03  3.10049169e-02 -9.71544534e-04
   -1.43378153e-02 -3.69089618e-02 -1.22089386e-02 -1.65273063e-02
    4.13679741e-02  3.75998281e-02  1.25779398e-02 -3.86717096e-02
    1.19196065e-02  1.57039203e-02 -2.09974647e-02 -2.65406724e-02
    4.07615937e-02  3.05179842e-02  2.42294557e-02 -2.92984005e-02
    2.48077177e-02  5.47824055e-03 -2.89169680e-02  2.27760710e-02
   -3.68920453e-02 -4.95482087e-02  3.03271078e-02 -1.67090520e-02
   -2.15751175e-02 -2.03405377e-02  4.90800478e-02  4.42004539e-02
    2.56790780e-02 -2.31497772e-02 -4.42387722e-02  3.33431400e-02]
  [-3.59115824e-02  2.08589919e-02  5.27602434e-03 -9.37887281e-03
   -2.10944172e-02 -1.63923614e-02  4.65950258e-02 -3.57266515e-03
   -2.20087171e-02 -3.92410047e-02  1.37251057e-02 -4.33124602e-04
    4.92398627e-02  1.36382096e-02  1.73647739e-02  1.77670233e-02
   -3.44641432e-02  4.73541878e-02  8.40761513e-03  4.91264947e-02
   -3.42836604e-02  1.91582553e-02  2.01663114e-02 -3.24656963e-02
   -2.80182119e-02  1.93910263e-02 -1.97934154e-02  2.09451057e-02
    1.84430145e-02 -2.08478104e-02 -3.53882909e-02  4.34654243e-02
    3.50732543e-02 -2.29730494e-02 -3.24084759e-02  2.44993307e-02
   -3.91315296e-03 -4.52718884e-03 -4.81388569e-02  3.48488577e-02
    4.63758595e-02 -3.49059701e-02 -2.51142029e-02  4.51564305e-02
    1.08334795e-02  2.20250376e-02  4.06344980e-03  3.21080536e-03
   -1.78120285e-03  2.75227539e-02  2.50347145e-02  3.57781164e-02
    4.14508842e-02 -4.88107279e-03  4.19248007e-02  4.37479876e-02
   -1.11952201e-02 -4.81789000e-02  4.61844914e-02 -4.36522141e-02
   -9.79460776e-04  1.54298209e-02 -4.64253202e-02 -3.31558734e-02
    3.92955579e-02 -7.20155239e-03  4.15089764e-02  4.40970771e-02
    3.89071368e-02  2.55157799e-03 -4.02306095e-02  4.63391282e-02
   -4.71559055e-02 -2.74949558e-02 -4.63455319e-02  7.11698458e-03
    3.02663185e-02  3.18014137e-02  2.39456333e-02  1.55003183e-02
    3.80670466e-02 -4.17794473e-02  4.03799899e-02 -4.64897864e-02
   -1.08037107e-02  3.11610438e-02 -3.21580917e-02  4.42355871e-03
    3.04650515e-04  3.59716527e-02 -4.05181050e-02 -2.77714133e-02
    4.74738739e-02 -2.97789816e-02 -2.01371443e-02 -2.85564419e-02
    1.26471557e-02  3.64111103e-02 -3.33194509e-02 -6.60971552e-03
    3.74400057e-02 -1.23625286e-02 -3.92608158e-02  1.06193796e-02
    3.87505181e-02  1.00596920e-02  2.02856958e-04 -2.88255140e-03
    1.11591443e-02  1.29307248e-02 -3.54615562e-02  2.02265419e-02
    3.13002504e-02  1.15481503e-02 -3.84966247e-02  4.52140719e-03
    2.84446739e-02  1.14953294e-02 -4.72129695e-02  5.22055477e-03
   -1.79020166e-02  3.22141163e-02 -2.26306077e-02 -2.45692264e-02
    1.89454444e-02  3.79525088e-02  4.71817367e-02  3.82001661e-02]
  [ 2.84221806e-02 -2.37033851e-02  3.98677588e-03  3.41418125e-02
   -1.58490650e-02  4.21768092e-02 -1.88158397e-02  4.01492380e-02
   -2.73007639e-02 -7.44471699e-03  8.16166401e-03 -1.58831105e-02
   -4.44130562e-02 -4.30429950e-02  1.26409195e-02 -9.11878422e-03
   -4.31329869e-02 -1.31073222e-02 -3.70266922e-02  1.44015662e-02
   -1.04658008e-02 -1.34580135e-02 -4.23724167e-02 -4.86696735e-02
   -1.43713877e-03 -4.87720966e-02  3.78739499e-02 -2.90668495e-02
   -4.25593928e-03 -1.83375850e-02  4.39928845e-03 -6.45779073e-04
    3.07251252e-02 -4.40380462e-02  4.42527644e-02  1.26951933e-03
   -6.92967325e-03  4.41037752e-02  1.92197226e-02  9.78195667e-03
   -2.46602185e-02 -7.13096932e-03 -3.65925543e-02 -4.65849303e-02
   -2.66242158e-02  4.77626957e-02 -2.50626802e-02 -3.91223058e-02
   -1.36644952e-02  1.51385553e-02  3.96771170e-02  4.13556211e-02
   -9.90567356e-03 -3.07295807e-02 -2.87271496e-02 -3.24951895e-02
   -3.78066301e-03 -4.21069562e-04  1.07317194e-02  2.40976475e-02
   -3.31627205e-03  2.53432654e-02 -2.07371358e-02 -7.33792782e-03
    4.58741076e-02  3.00190337e-02 -1.89627167e-02  4.37664986e-03
    8.89388472e-03 -1.58028826e-02  3.12719680e-02 -2.39773523e-02
   -4.37222980e-02  4.77913134e-02  1.28597058e-02 -6.15016371e-03
   -3.75545248e-02  8.53694975e-04  3.02889980e-02  2.43637078e-02
    1.71693303e-02 -3.85473259e-02  1.96368434e-02 -9.49463993e-03
    8.67988914e-03 -3.41167338e-02 -3.98877747e-02  6.04167581e-05
   -1.19357593e-02  4.61945571e-02 -1.29919760e-02 -2.84509417e-02
   -2.84285676e-02  6.27901405e-03  3.10049169e-02 -9.71544534e-04
   -1.43378153e-02 -3.69089618e-02 -1.22089386e-02 -1.65273063e-02
    4.13679741e-02  3.75998281e-02  1.25779398e-02 -3.86717096e-02
    1.19196065e-02  1.57039203e-02 -2.09974647e-02 -2.65406724e-02
    4.07615937e-02  3.05179842e-02  2.42294557e-02 -2.92984005e-02
    2.48077177e-02  5.47824055e-03 -2.89169680e-02  2.27760710e-02
   -3.68920453e-02 -4.95482087e-02  3.03271078e-02 -1.67090520e-02
   -2.15751175e-02 -2.03405377e-02  4.90800478e-02  4.42004539e-02
    2.56790780e-02 -2.31497772e-02 -4.42387722e-02  3.33431400e-02]]]

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline

model_0 = Pipeline([
    ('tfidf', TfidfVectorizer()),
    ('clf', MultinomialNB()),

])

In [16]:
X = df.drop('same_security', axis=1)
y = df['same_security']

In [17]:
X

,description_x,description_y
0,first trust dow jones internet,first trust dj internet idx
1,schwab intl large company index etf,schwab strategic tr fundamental intl large co ...
2,vanguard small cap index adm,vanguard small-cap index fund inst
3,duke energy corp new com new isin #us4 sedol #...,duke energy corp new com new isin #us26441c204...
4,visa inc class a,visa inc.
...,...,...
2137,delta air lines inc com,delta air lines inc dela new
2138,cognizant tech solutns a,cognizant tech solutions corp
2139,pimco investment grade corporate bond fund - c...,fid conservative income bond fund
2140,eli lilly & co com,lilly eli &co com npv
2141,dfa comm strategy i,dfa commodity strategy port

In [18]:
y

0       1
1       1
2       0
3       1
4       1
       ..
2137    1
2138    1
2139    0
2140    1
2141    1
Name: same_security, Length: 2142, dtype: int64

In [19]:
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.base import TransformerMixin, BaseEstimator

# Custom transformer to select a column for the pipeline
class ColumnSelector(BaseEstimator, TransformerMixin):
    def __init__(self, column):
        self.column = column

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        return X[self.column]

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create separate pipelines for each text column
pipeline_text1 = Pipeline([
    ('selector', ColumnSelector(column='description_x')),
    ('tfidf', TfidfVectorizer())
])

pipeline_text2 = Pipeline([
    ('selector', ColumnSelector(column='description_y')),
    ('tfidf', TfidfVectorizer())
])

# Combine features from both pipelines
feature_union = FeatureUnion([
    ('text1_features', pipeline_text1),
    ('text2_features', pipeline_text2)
])

# Final pipeline with feature union and classifier
model_pipeline = Pipeline([
    ('features', feature_union),
    ('classifier', LogisticRegression())
])

# Fit the model
model_pipeline.fit(X_train, y_train)

# Make predictions
predictions = model_pipeline.predict(X_test)

# Evaluate the model's performance
from sklearn.metrics import accuracy_score
print(f"Model accuracy: {accuracy_score(y_test, predictions)}")

Model accuracy: 0.8997668997668997

In [20]:
import pandas as pd

def check_similarity(sentence1, sentence2, model):
    """
    Checks the similarity between two sentences using the provided model.
    
    Parameters:
    - sentence1: The first sentence as a string.
    - sentence2: The second sentence as a string.
    - model: The trained model pipeline.
    
    Returns:
    - similarity: The predicted similarity (1 for similar, 0 for not similar).
    """
    # Create a DataFrame with the sentences
    data = pd.DataFrame({'description_x': [sentence1], 'description_y': [sentence2]})
    
    # Use the model to predict similarity
    prediction = model.predict(data)
    
    # Return the prediction
    return prediction[0]

# Example usage
# Assuming 'model_pipeline' is your trained model pipeline
sentence1 = "There is fire in garden."
sentence2 = "This is the second sentence."
similarity = check_similarity(sentence1, sentence2, model_pipeline)
print(f"Similarity: {similarity}")

Similarity: 1

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
import numpy as np

# Sample DataFrame
df = pd.DataFrame({
    'description_x': ['This is the first description', 'Here is another description'],
    'description_y': ['This is the second description', 'This description is different']
})

# Initialize the TfidfVectorizer
vectorizer = TfidfVectorizer()

# Vectorize 'description_x' and 'description_y'
vectorized_x = vectorizer.fit_transform(df['description_x'])
vectorized_y = vectorizer.transform(df['description_y'])  # Use transform to ensure the same feature space

# Compute cosine similarity
# Note: cosine_similarity returns a matrix, we need to extract diagonal elements for pairwise similarity
similarity_scores = cosine_similarity(vectorized_x, vectorized_y).diagonal()

# Store the similarity scores in a new column
df['cosine_similarity'] = similarity_scores

# Display the updated DataFrame
print(df)

                   description_x                   description_y  \
0  This is the first description  This is the second description
1    Here is another description   This description is different

   cosine_similarity
0           0.866475
1           0.411207

In [24]:
test_df = pd.read_csv('archive/test.csv')
test_df.head()

,test_id,description_x,description_y,same_security
0,0,semtech corp,semtech corporation,NaN
1,1,vanguard mid cap index,vanguard midcap index - a,NaN
2,2,spdr gold trust gold shares,spdr gold trust spdr gold shares,NaN
3,3,vanguard total bond index adm,vanguard total bond market index,NaN
4,4,oakmark international fund class i,oakmark international cl i,NaN

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Initialize the TfidfVectorizer
vectorizer = TfidfVectorizer()

# Vectorize 'description_x' and 'description_y' in test_df
vectorized_x = vectorizer.fit_transform(test_df['description_x'])
vectorized_y = vectorizer.transform(test_df['description_y'])  # Use transform to ensure the same feature space

# Compute cosine similarity
# Note: cosine_similarity returns a matrix, we need to extract diagonal elements for pairwise similarity
similarity_scores = cosine_similarity(vectorized_x, vectorized_y).diagonal()

# Store the similarity scores in a new column
test_df['cosine_similarity'] = similarity_scores

# Display the updated DataFrame
print(test_df)

     test_id                                   description_x  \
0          0                                    semtech corp
1          1                          vanguard mid cap index
2          2                     spdr gold trust gold shares
3          3                   vanguard total bond index adm
4          4              oakmark international fund class i
..       ...                                             ...
511      511  at&t inc com isin #us00206r1023 sedol #2831811
512      512     vanguard total international bond index etf
513      513                wisdomtree japan hedged equity -
514      514        templeton global bond fund advisor class
515      515                             trp health sciences

                                     description_y  same_security  \
0                              semtech corporation            NaN
1                        vanguard midcap index - a            NaN
2                 spdr gold trust spdr gold shares            NaN
3                 vanguard total bond market index            NaN
4                       oakmark international cl i            NaN
..                                             ...            ...
511  franklin res inc com isin #us8 sedol #2350684            NaN
512           vanguard total international bond et            NaN
513                     wisdomtree japan hedged eq            NaN
514                       templeton glbal bond adv            NaN
515             t. rowe price health sciences fund            NaN

     cosine_similarity
0             0.673422
1             0.307456
2             0.958085
3             0.715294
4             0.758911
..                 ...
511           0.380581
512           0.859225
513           0.900933
514           0.343521
515           0.617943

[516 rows x 5 columns]