In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print("Modules imported")

Modules imported

In [2]:
train_data = pd.read_csv('archive/train.csv')
train_data.head()

,Unnamed: 0,description_x,description_y,ticker_x,ticker_y,same_security
0,0,first trust dow jones internet,first trust dj internet idx,FDN,FDN,True
1,1,schwab intl large company index etf,schwab strategic tr fundamental intl large co ...,FNDF,FNDF,True
2,2,vanguard small cap index adm,vanguard small-cap index fund inst,VSMAX,VSCIX,False
3,3,duke energy corp new com new isin #us4 sedol #...,duke energy corp new com new isin #us26441c204...,DUK,DUK,True
4,4,visa inc class a,visa inc.,V,V,True

In [3]:
train_data.drop(train_data.columns[0], axis = 1, inplace = True)
train_data.head()

,description_x,description_y,ticker_x,ticker_y,same_security
0,first trust dow jones internet,first trust dj internet idx,FDN,FDN,True
1,schwab intl large company index etf,schwab strategic tr fundamental intl large co ...,FNDF,FNDF,True
2,vanguard small cap index adm,vanguard small-cap index fund inst,VSMAX,VSCIX,False
3,duke energy corp new com new isin #us4 sedol #...,duke energy corp new com new isin #us26441c204...,DUK,DUK,True
4,visa inc class a,visa inc.,V,V,True

In [4]:
train_data['same_security'] = train_data['same_security'].astype('int')
train_data.head()

,description_x,description_y,ticker_x,ticker_y,same_security
0,first trust dow jones internet,first trust dj internet idx,FDN,FDN,1
1,schwab intl large company index etf,schwab strategic tr fundamental intl large co ...,FNDF,FNDF,1
2,vanguard small cap index adm,vanguard small-cap index fund inst,VSMAX,VSCIX,0
3,duke energy corp new com new isin #us4 sedol #...,duke energy corp new com new isin #us26441c204...,DUK,DUK,1
4,visa inc class a,visa inc.,V,V,1

In [5]:
df = train_data[['description_x', 'description_y', 'same_security']]
df.head()

,description_x,description_y,same_security
0,first trust dow jones internet,first trust dj internet idx,1
1,schwab intl large company index etf,schwab strategic tr fundamental intl large co ...,1
2,vanguard small cap index adm,vanguard small-cap index fund inst,0
3,duke energy corp new com new isin #us4 sedol #...,duke energy corp new com new isin #us26441c204...,1
4,visa inc class a,visa inc.,1

In [6]:
df.same_security.value_counts()

same_security
1    1613
0     529
Name: count, dtype: int64

In [7]:
from tensorflow.keras.layers import TextVectorization

text_vectorizer = TextVectorization(max_tokens=None,
                                    standardize = "lower_and_strip_punctuation",
                                    split = "whitespace",
                                    ngrams = None,
                                    output_mode = 'int',
                                    output_sequence_length = None)

In [8]:
train_sentences1 = train_data.description_x
train_sentences2 = train_data.description_y

text_vectorizer.adapt(train_sentences1)

In [9]:
sample_sentence = "This is a sample sentence, there is flood on my street, what are you doing? I am just waiting at the door staep"
text_vectorizer([sample_sentence])

<tf.Tensor: shape=(1, 23), dtype=int64, numpy=
array([[   1,  319,   11,    1,    1,    1,  319,    1,    1,    1,  574,
           1,    1,    1,    1,   33,  772,    1,    1, 1380,  148,    1,
           1]])>

In [10]:
train_sentences1 = train_data.description_x
train_sentences2 = train_data.description_y

text_vectorizer.adapt(train_sentences1)

vectorized_sentences1 = text_vectorizer(train_sentences1)
vectorized_sentences2 = text_vectorizer(train_sentences2)

In [11]:
import random

random_sentence = random.choice(train_sentences1)
print(f'Original Sentence: {random_sentence}')
print(f'Vectorized Sentence: {text_vectorizer([random_sentence])}')

Original Sentence: vanguard short term bond fund
Vectorized Sentence: [[ 2 45 37  8  4]]

In [12]:
print(f'Original Sentence: pimco real return insitutional')
print(text_vectorizer(['pimco real return insitutional']))

Original Sentence: pimco real return insitutional
tf.Tensor([[ 14  86  19 478]], shape=(1, 4), dtype=int64)

In [13]:
from tensorflow.keras.layers import Embedding

embedding = Embedding(input_dim = 10000,
                      output_dim = 128,
                      )

embedding

In [14]:
random_sentence = random.choice(train_sentences1)
print(f'Original Sentence : {random_sentence}')
print(f'Embedded Sentence: {embedding(text_vectorizer([random_sentence]))}')

Original Sentence : vanguard total bond market index admiral
Embedded Sentence: [[[ 0.04972912  0.02167959  0.01448884  0.03832227 -0.03293025
   -0.01700097  0.00252252 -0.02327517  0.03905145 -0.03003513
    0.02811993  0.03377074 -0.02857522 -0.03790237 -0.02889578
    0.04766691 -0.03581947 -0.03654853  0.02330915 -0.04740936
    0.01191243  0.0151052  -0.0329934   0.03950962  0.02747003
   -0.00596999  0.02790742 -0.03015505  0.01599873  0.02928721
    0.01242314  0.02842328 -0.0319524  -0.03221019  0.03413293
    0.02205975 -0.01500729 -0.04200698  0.00293993 -0.0267465
    0.02003782  0.01220851  0.02652271 -0.00909418  0.00729579
   -0.00644707 -0.01191749 -0.00343474 -0.01456592  0.02396716
    0.0257684   0.00221324  0.03549457 -0.04493088  0.02494386
    0.03639329 -0.00204246  0.03989157 -0.01311694  0.04443611
    0.02727455 -0.00295615  0.01233989  0.0004253   0.02133134
    0.0107165  -0.01451246 -0.00527091  0.04199663  0.03430412
   -0.01255875 -0.00513102  0.0390312  -0.04420301 -0.01605972
    0.0250217  -0.04296167 -0.0307341   0.0433442  -0.0365277
   -0.00363957  0.03224853  0.04136444 -0.00375521  0.02915157
   -0.01973012  0.04250692  0.04433657  0.04376981 -0.03019158
   -0.02577438 -0.01104206  0.04423385  0.01998342  0.03074118
   -0.02570356 -0.04938035 -0.0272326  -0.01530071 -0.02191726
   -0.04531929  0.00832958  0.04045388 -0.02801877 -0.01549869
    0.03913317  0.00580806 -0.01482942  0.02952072  0.00317388
    0.03998976  0.0379965  -0.02659976  0.01543241 -0.00468171
    0.00377148  0.01395822 -0.03644899  0.00476825 -0.01958721
   -0.0473565  -0.02930744  0.01802793 -0.02056172 -0.04923443
    0.034845    0.01452377  0.01373157]
  [ 0.01847298 -0.02244203  0.04188236 -0.00646454  0.02168817
    0.01990328 -0.00086797 -0.00600826 -0.00488215  0.00248262
   -0.02184024 -0.00256071 -0.03625214  0.00287139 -0.04813315
    0.0463729  -0.020556    0.04541161  0.03138671 -0.02829131
   -0.0327154  -0.01172    -0.00867178  0.01019346 -0.0343519
    0.00932003 -0.02382812 -0.00404222  0.03678088  0.04189033
   -0.03844471 -0.02002454  0.02086792 -0.02341491 -0.02635149
    0.00931454  0.00768916  0.03734319  0.04333129  0.00098919
    0.04666264  0.00037432 -0.01123812 -0.02097362  0.03404405
   -0.00711514  0.00990643  0.03605707  0.04202595  0.01880983
   -0.0012776   0.04932171  0.01184914 -0.02643934 -0.01278167
   -0.02428893 -0.04207916 -0.03304978  0.00470056 -0.01111598
   -0.04550637  0.02919041 -0.0269758   0.00680125 -0.04070306
   -0.00385999  0.01722688  0.04695027 -0.02676783 -0.00054765
    0.01558067  0.04185495 -0.03498294  0.04475245  0.01552205
   -0.02836126  0.02869973  0.0456695  -0.03036059 -0.02080231
    0.03112641  0.00258665 -0.0078826   0.00596005 -0.00849197
   -0.02125433  0.00571374  0.04877606 -0.01613669 -0.04809442
    0.00263076  0.03248835 -0.0159778   0.02635331 -0.03058228
    0.03693911 -0.03791947 -0.00021027  0.04509557 -0.01891233
   -0.00053749  0.01352819  0.04353112  0.0499248  -0.00194601
   -0.03338756  0.0202127  -0.00831555  0.01803732  0.01556325
   -0.01992562  0.03317064  0.02377741 -0.02573499 -0.02681015
    0.00293238  0.00736642  0.00961195 -0.00820897 -0.04865045
    0.00403416 -0.03655342  0.0002557   0.04099739 -0.04507463
   -0.04563917  0.00974249 -0.04011139]
  [ 0.0273896  -0.00586674 -0.01505844  0.00349708 -0.03393769
   -0.02794605 -0.02710064 -0.01243235  0.04034961 -0.00677329
    0.03571287 -0.0366612   0.04770733  0.0274702  -0.04405319
    0.03880935  0.0375286   0.03997803  0.00077391  0.01965983
    0.00020586  0.04766319  0.04055284 -0.02801117 -0.0327621
   -0.0142324  -0.0335161  -0.01726996  0.01798636  0.03192878
   -0.01560754  0.02904129 -0.03847697  0.00986469  0.03554248
   -0.02885398 -0.01410983  0.03169708 -0.03635843 -0.00681553
    0.01221166 -0.04552076 -0.04219831 -0.01187269 -0.03463144
    0.00419778 -0.01042856 -0.00724735 -0.04743483 -0.0308092
    0.02967329 -0.03810434 -0.02705361  0.04852346  0.04085096
   -0.03780714 -0.03265666 -0.0078676  -0.02062553  0.03282585
    0.02425993  0.04670458  0.01967395 -0.01142576 -0.01185297
   -0.00919931  0.03416859  0.04382342 -0.04706934  0.02995665
    0.04959394 -0.00971382  0.00782733  0.03983367 -0.02264223
    0.02670843  0.00123278  0.01058724  0.03199789 -0.01240937
    0.0036461  -0.04614383 -0.00221735 -0.00606847  0.03410337
    0.01500107  0.02162592 -0.03265303 -0.02872241 -0.03363563
    0.03312465 -0.04910363  0.02976498  0.02162195  0.04436119
   -0.04815428 -0.00125585 -0.00368083  0.04876718 -0.01316962
   -0.00578045 -0.02387261 -0.04741463 -0.03105071  0.03470551
   -0.0478402   0.04874367  0.01508471 -0.00540924 -0.00559585
   -0.01514499  0.02332635 -0.0202847   0.00232021  0.01883749
    0.04205454 -0.0294516   0.00890542  0.02350154  0.00067048
    0.02171436 -0.01015624  0.03721685  0.00562681 -0.03978192
    0.0255552   0.03800875 -0.04495341]
  [ 0.00092645  0.04808042  0.00196655  0.04129871 -0.02292405
    0.00725983  0.01161319 -0.000326    0.03545209 -0.04817719
    0.03488575 -0.00492451 -0.0428152   0.02929987 -0.03655799
    0.0468726  -0.02923246 -0.01574118 -0.02209387  0.02102591
    0.01222891 -0.03945161 -0.01609696 -0.04044884 -0.0147648
   -0.04081333  0.00072335 -0.03227963  0.00951819 -0.01256434
    0.02963762 -0.01381282  0.00094998  0.02738799  0.03529241
    0.03989301  0.04960141  0.03488758 -0.00348296  0.04484724
    0.01834632 -0.02570917 -0.00900127 -0.03934249 -0.0140912
   -0.00454506  0.02324314  0.00444435 -0.03418291  0.04020684
   -0.01165473 -0.00116384  0.01712156  0.00306009  0.0274925
   -0.03013171  0.02696666 -0.03279954  0.03806942  0.01128
   -0.01915005  0.03830507 -0.00657195  0.03229684  0.00557158
    0.02602222  0.01809281 -0.03312054  0.01937139 -0.04183569
   -0.03166839 -0.00525304  0.00720446  0.00873903 -0.00378889
    0.0497416  -0.04360227 -0.0372543   0.0083876  -0.04444863
    0.02909825 -0.04082099  0.03148389 -0.03905449  0.0044424
    0.03447776  0.01890384  0.03601233  0.02264801  0.00240956
    0.03216565  0.04606041 -0.0001372   0.02781074  0.00632992
   -0.01810097 -0.02650869  0.02148661  0.01524284 -0.04715965
   -0.04930202  0.00208995 -0.02104284  0.04896596 -0.04591776
   -0.02120875 -0.00823689 -0.00240244 -0.02982395 -0.01876223
   -0.03570179 -0.00513389  0.02826139  0.04440297 -0.04501524
   -0.00609415 -0.00607618 -0.00295713 -0.00861769 -0.04920813
    0.03218682 -0.01157651  0.04848044  0.00531231  0.00502566
   -0.00740472 -0.03979911 -0.04313066]
  [-0.04786615  0.00898366 -0.01983746 -0.04780642 -0.01365732
   -0.00212719 -0.04265879  0.01967416  0.00590339 -0.0100785
   -0.0022635  -0.02698151  0.00893696  0.04455372  0.0126563
    0.01123686  0.01902724  0.03714711 -0.04995505  0.04468651
   -0.02238975  0.01181209 -0.04452158 -0.03450425  0.01817094
   -0.04267764  0.03489879 -0.01542189 -0.02825813 -0.00213528
    0.03337901 -0.01581281  0.04505731  0.04538414 -0.04757675
   -0.04786677  0.01979462 -0.01801019  0.00994438  0.00395834
    0.00391978  0.01156897  0.03346955 -0.01294035  0.03843239
   -0.02982817 -0.00860807 -0.02430365 -0.00121068 -0.00857891
   -0.00933552 -0.04801954  0.01166316 -0.03536136  0.01278814
    0.0436823   0.03245865  0.04545617  0.01520951 -0.03382444
    0.02050166 -0.01880567  0.03573104  0.01142793 -0.01969755
    0.00510269 -0.00546579  0.04894669  0.0482606  -0.02497127
    0.04710079  0.01199213 -0.02336892  0.0277991   0.00894997
   -0.0264576  -0.00034336  0.02906872 -0.04257662  0.03074652
    0.01331545  0.00303816 -0.00104605  0.00030958  0.04544467
   -0.00582826 -0.01248967 -0.0462542   0.04779747  0.00855783
   -0.04461804 -0.0009475  -0.03693463  0.02246312  0.02074483
   -0.00241365  0.00379224 -0.00161149 -0.0485922  -0.0268219
    0.04965052 -0.00863256  0.01882669  0.01720407 -0.00490524
    0.03137738 -0.02462516 -0.00347978  0.00795604  0.01013942
   -0.02148751 -0.04580207  0.03365624  0.02500128 -0.03224804
    0.04671255 -0.02415401 -0.02407676  0.00652517 -0.02159276
    0.04328604 -0.02374517  0.00556003  0.04474243  0.03066077
    0.02322013 -0.00079533 -0.02494676]
  [-0.04023921 -0.00715352  0.00733591  0.04893298  0.01915551
    0.00870805  0.03595178 -0.03408372 -0.02568457 -0.00630753
   -0.00319235  0.04972832 -0.02769854 -0.02367081  0.02480898
   -0.02341259 -0.03368107  0.03605593  0.00605921  0.0005541
    0.04522244  0.02591493 -0.04595385  0.01815737  0.01968806
    0.02501592  0.04127285 -0.03935169 -0.03699042  0.01234967
   -0.006594    0.03545976 -0.00678564 -0.0358377   0.00568627
    0.01620093 -0.01291833  0.00911229 -0.0287716   0.0106777
   -0.01293952  0.00747633 -0.03840879  0.00714477 -0.02758995
    0.02458474  0.00545216  0.02909387 -0.01785337 -0.04402849
   -0.00367011 -0.01506178  0.00383002 -0.01829607 -0.0050665
    0.02014652  0.00989771 -0.0430257   0.04477036  0.00138236
    0.0369077  -0.01604978 -0.03014433 -0.0430766  -0.01812054
   -0.00041895  0.02250924  0.00560089 -0.00855371 -0.02207283
    0.01645948 -0.02969682 -0.0230412   0.02928021 -0.01766877
    0.0115841   0.04864189  0.02690179  0.00459837  0.04837209
    0.01811432 -0.01611999  0.018116    0.04022557  0.02839733
    0.02030301 -0.03747366  0.02135866 -0.04172567  0.00082023
    0.01177191 -0.02730134  0.041576   -0.04737462 -0.0488385
    0.02432353 -0.04681334 -0.04312918  0.00897415 -0.03230841
    0.0257686  -0.01469854 -0.03691745  0.00336016  0.0272012
   -0.0368399  -0.00693768 -0.0490116   0.03822757 -0.02271408
   -0.01034684  0.02266935  0.04028071  0.0213642  -0.0010866
   -0.00894073 -0.01784001  0.03330559  0.04918559  0.04229793
    0.01501049  0.03126724 -0.00226571 -0.00374059 -0.03777307
    0.02674532  0.02871228  0.04424312]]]

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline

model_0 = Pipeline([
    ('tfidf', TfidfVectorizer()),
    ('clf', MultinomialNB()),

])

In [16]:
X = df.drop('same_security', axis=1)
y = df['same_security']

In [17]:
X

,description_x,description_y
0,first trust dow jones internet,first trust dj internet idx
1,schwab intl large company index etf,schwab strategic tr fundamental intl large co ...
2,vanguard small cap index adm,vanguard small-cap index fund inst
3,duke energy corp new com new isin #us4 sedol #...,duke energy corp new com new isin #us26441c204...
4,visa inc class a,visa inc.
...,...,...
2137,delta air lines inc com,delta air lines inc dela new
2138,cognizant tech solutns a,cognizant tech solutions corp
2139,pimco investment grade corporate bond fund - c...,fid conservative income bond fund
2140,eli lilly & co com,lilly eli &co com npv
2141,dfa comm strategy i,dfa commodity strategy port

In [18]:
y

0       1
1       1
2       0
3       1
4       1
       ..
2137    1
2138    1
2139    0
2140    1
2141    1
Name: same_security, Length: 2142, dtype: int64

In [19]:
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.base import TransformerMixin, BaseEstimator

# Custom transformer to select a column for the pipeline
class ColumnSelector(BaseEstimator, TransformerMixin):
    def __init__(self, column):
        self.column = column

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        return X[self.column]

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create separate pipelines for each text column
pipeline_text1 = Pipeline([
    ('selector', ColumnSelector(column='description_x')),
    ('tfidf', TfidfVectorizer())
])

pipeline_text2 = Pipeline([
    ('selector', ColumnSelector(column='description_y')),
    ('tfidf', TfidfVectorizer())
])

# Combine features from both pipelines
feature_union = FeatureUnion([
    ('text1_features', pipeline_text1),
    ('text2_features', pipeline_text2)
])

# Final pipeline with feature union and classifier
model_pipeline = Pipeline([
    ('features', feature_union),
    ('classifier', LogisticRegression())
])

# Fit the model
model_pipeline.fit(X_train, y_train)

# Make predictions
predictions = model_pipeline.predict(X_test)

# Evaluate the model's performance
from sklearn.metrics import accuracy_score
print(f"Model accuracy: {accuracy_score(y_test, predictions)}")

Model accuracy: 0.8997668997668997

In [20]:
import pandas as pd

def check_similarity(sentence1, sentence2, model):
    """
    Checks the similarity between two sentences using the provided model.
    
    Parameters:
    - sentence1: The first sentence as a string.
    - sentence2: The second sentence as a string.
    - model: The trained model pipeline.
    
    Returns:
    - similarity: The predicted similarity (1 for similar, 0 for not similar).
    """
    # Create a DataFrame with the sentences
    data = pd.DataFrame({'description_x': [sentence1], 'description_y': [sentence2]})
    
    # Use the model to predict similarity
    prediction = model.predict(data)
    
    # Return the prediction
    return prediction[0]

# Example usage
# Assuming 'model_pipeline' is your trained model pipeline
sentence1 = "There is fire in garden."
sentence2 = "This is the second sentence."
similarity = check_similarity(sentence1, sentence2, model_pipeline)
print(f"Similarity: {similarity}")

Similarity: 1

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
import numpy as np

# Sample DataFrame
df = pd.DataFrame({
    'description_x': ['This is the first description', 'Here is another description'],
    'description_y': ['This is the second description', 'This description is different']
})

# Initialize the TfidfVectorizer
vectorizer = TfidfVectorizer()

# Vectorize 'description_x' and 'description_y'
vectorized_x = vectorizer.fit_transform(df['description_x'])
vectorized_y = vectorizer.transform(df['description_y'])  # Use transform to ensure the same feature space

# Compute cosine similarity
# Note: cosine_similarity returns a matrix, we need to extract diagonal elements for pairwise similarity
similarity_scores = cosine_similarity(vectorized_x, vectorized_y).diagonal()

# Store the similarity scores in a new column
df['cosine_similarity'] = similarity_scores

# Display the updated DataFrame
print(df)

                   description_x                   description_y  \
0  This is the first description  This is the second description
1    Here is another description   This description is different

   cosine_similarity
0           0.866475
1           0.411207

In [22]:
test_df = pd.read_csv('archive/test.csv')
test_df.head()

,test_id,description_x,description_y,same_security
0,0,semtech corp,semtech corporation,NaN
1,1,vanguard mid cap index,vanguard midcap index - a,NaN
2,2,spdr gold trust gold shares,spdr gold trust spdr gold shares,NaN
3,3,vanguard total bond index adm,vanguard total bond market index,NaN
4,4,oakmark international fund class i,oakmark international cl i,NaN

In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Initialize the TfidfVectorizer
vectorizer = TfidfVectorizer()

# Vectorize 'description_x' and 'description_y' in test_df
vectorized_x = vectorizer.fit_transform(test_df['description_x'])
vectorized_y = vectorizer.transform(test_df['description_y'])  # Use transform to ensure the same feature space

# Compute cosine similarity
# Note: cosine_similarity returns a matrix, we need to extract diagonal elements for pairwise similarity
similarity_scores = cosine_similarity(vectorized_x, vectorized_y).diagonal()

# Store the similarity scores in a new column
test_df['cosine_similarity'] = similarity_scores

# Display the updated DataFrame
print(test_df)

     test_id                                   description_x  \
0          0                                    semtech corp
1          1                          vanguard mid cap index
2          2                     spdr gold trust gold shares
3          3                   vanguard total bond index adm
4          4              oakmark international fund class i
..       ...                                             ...
511      511  at&t inc com isin #us00206r1023 sedol #2831811
512      512     vanguard total international bond index etf
513      513                wisdomtree japan hedged equity -
514      514        templeton global bond fund advisor class
515      515                             trp health sciences

                                     description_y  same_security  \
0                              semtech corporation            NaN
1                        vanguard midcap index - a            NaN
2                 spdr gold trust spdr gold shares            NaN
3                 vanguard total bond market index            NaN
4                       oakmark international cl i            NaN
..                                             ...            ...
511  franklin res inc com isin #us8 sedol #2350684            NaN
512           vanguard total international bond et            NaN
513                     wisdomtree japan hedged eq            NaN
514                       templeton glbal bond adv            NaN
515             t. rowe price health sciences fund            NaN

     cosine_similarity
0             0.673422
1             0.307456
2             0.958085
3             0.715294
4             0.758911
..                 ...
511           0.380581
512           0.859225
513           0.900933
514           0.343521
515           0.617943

[516 rows x 5 columns]

In [25]:
random_index = random.randint(0, test_df.shape[0])

random_row = test_df.iloc[random_index]
description_x = random_row['description_x']
description_y = random_row['description_y']
cosine_similarity = random_row['cosine_similarity']

print(f"The Original Sentence is: {description_x}")
print(f"The Sentence to be compared is: {description_y}")
print(f"Similarity between the sentences is: {cosine_similarity}")

The Original Sentence is: ishares core msci emerging markets etf
The Sentence to be compared is: harding loevner emerging mkts
Similarity between the sentences is: 0.30954262834941276